[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["node_modules"]
evm_version = "cancun"
remapping = [
    "solady/=node_modules/solady/",
    "@openzeppelin/=node_modules/@openzeppelin/contracts/",
    "forge-std/src/=node_modules/forge-std/",
]

# optimizer_runs = 1_000_000
optimizer = true
optimizer_runs = 1

block_timestamp = 100_000_0000

[doc]
out = "docs/foundry-docs"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci.invariant]
depth = 15
runs = 10

[profile.debug_invariant.invariant]
depth = 150
runs = 120
fail_on_revert = true

[rpc_endpoints]
mainnet = 'https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
arbitrum = 'https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
base = 'https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
tenderly_eth = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 1, url = '${TENDERLY_DEV_NET_RPC_URL}' }
tenderly_arb = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 42161, url = '${TENDERLY_DEV_NET_ARB}' }

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}", chain = 146, url = "https://sonicscan.org/" }
