name: Continuous Integration

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "assets/**"
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.3.6

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Check contracts are linted
        run: forge fmt --check

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.3.6

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate fuzz seed that changes every 3 weeks to avoid burning through RPC allowance
        run: |
          seed=$(echo $(($EPOCHSECONDS / 1814400)))
          echo "FOUNDRY_FUZZ_SEED=$seed" >> $GITHUB_ENV

      - name: Show Foundry config
        run: forge config

      - name: Run local unit, fuzz and invariant tests
        run: >-
          FOUNDRY_PROFILE=ci forge test --dynamic-test-linking
          --skip test/integrations test/wrapper/ConvexWrapper.t.sol test/wrapper/SNukeWrapper.t.sol script
          --no-match-test=testFork
          --no-match-contract='(Fork|ConvexWrapperTest|^(PYUSDTest|PXETH_STETH_Test|REUSD_SCRVUSD_Test|RSUP_WETH_Test|AggregationRouterTest|RobinhoodStockTokenResolverTest|SNukeWrapperTest|apyUSDWrapperTest|aWETHWrapperTest|AddLiquidityAnyOneTokenTest|ZapCombineToAnyTokenTest|RedeemAnyTokenTest|RemoveLiquidityAnyOneTokenTest|ZapSupplyAnyTokenTest|SwapAnyTokenForPtTest|SwapAnyTokenForYTTest|SwapPtForAnyTokenTest|SwapYtForAnyTokenTest)$)'
          --threads=2 --show-progress --suppress-successful-traces

  codespell:
    name: Run codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          ignore_words_list: amountin
          skip: ./.git,pnpm-lock.yaml,*.pdf,node_modules,out,cache
